### PR TITLE
fix: changes to support linter API v2

### LINKED ISSUE #135: Support v2 Linter API
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

### PR DESCRIPTION
**Pull request by vzamanillo**
Fixed #135

### CODE REVIEW

**Comment by vzamanillo** [comment]
Some light to solve the test failures?

```
#!/bin/bash --login
${APM_SCRIPT_PATH} clean

Removing extraneous modules ✗
> husky@1.3.1 install node_modules/husky
> node husky install


npm WARN lifecycle npm is using /usr/share/atom-beta/resources/app/apm/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
sh: 1: node: not found
```

**Comment by ricardograca** [comment]
Thanks for the contribution. I'll check it out later today.

**Comment by Arcanemagus** [comment]
I think that's due to a bug in the older cache configuration that can cause "contamination" from a dependency update onto other branches. I'm putting up a PR to fix this.

**Comment by vzamanillo** [comment]
> I think that's due to a bug in the older cache configuration that can cause "contamination" from a dependency update onto other branches. I'm putting up a PR to fix this.

Thank you!

**Comment by Arcanemagus** [comment]
@vzamanillo can you rebase this on `master`? Your build should be fixed now.

**Comment by vzamanillo** [comment]
> @vzamanillo can you rebase this on `master`? Your build should be fixed now.

Done, I had to do a force push because in my branch there was a commit that reverted the initial changes I made in the package-lock file

**Pull request merged**
