### PR TITLE
chore: pin eslint to 4.12.0

### PR DESCRIPTION
**Pull request by ricardograca**
Pinning this to a version that works for now. Anyone that wants to check why newer versions are failing is free to submit a PR.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Looks like the "failure" was AppVeyor timing out for some reason: https://ci.appveyor.com/project/Arcanemagus/linter-erb/build/220#L47

Rebuilding the same commit worked 😉: https://ci.appveyor.com/project/Arcanemagus/linter-erb/build/223

**Comment by ricardograca** [comment]
Ok, I'll update the PR ASAP then.

**Comment by Arcanemagus** [comment]
Or just close it? There isn't really a need for it unless you _want_ to bump the minimum version.

**Comment by ricardograca** [comment]
Good point.

**Pull request closed without merging**
