### PR TITLE
Pass fileDir as ‘cwd’ to ruby process.

### PR DESCRIPTION
**Pull request by jmfederico**
This makes sure the ruby version used to lint the _erb_ template is the one specified on the project the user is working on.

### CODE REVIEW

**Comment by jmfederico** [comment]
To clarify, makes _Linter erb_ fully compatible with rbenv

**Comment by Arcanemagus** [comment]
Hmmm, btw, you should always do PR's from a branch, looks like the "give contributor's write access to PR branches" gave me write access to your `master` branch 😨.

**Comment by jmfederico** [comment]
Hi, ah, didn't see that option, didn't know it existed. Will check other PR's!

Thanks

**Comment by Arcanemagus** [comment]
It's generally a very good thing as it means the people you submit a PR to can fix things up before merging (like merging in `master` here), it's just safer for you if you do a PR from a branch. It's not like this is SVN where those are an arduous process 😛.

**Pull request merged**
