### PR TITLE
Test display of Atom version

### PR DESCRIPTION
**Pull request by Arcanemagus**
This is just a test of some CI script changes!

### CODE REVIEW

**Comment by ricardograca** [comment]
Looks good. I assume it's the part `Using Atom version: ...`

**Comment by Arcanemagus** [comment]
Yea, sorry just picked a random repo to test this on. The first build actually output _twice_, once correctly and once broken, so I'm still trying to find the right way to work around this.

The current script never actually shows the version for Atom.

**Comment by Arcanemagus** [comment]
The really annoying part is the current method, and everything I've tried so far works perfectly on Win10, but seems to be broken on the Server 2012 VMs used on AppVeyor.

**Comment by Arcanemagus** [comment]
Done testing for now, sorry for the spam!

**Comment by ricardograca** [comment]
No problem :) I hope it was useful.

**Comment by Arcanemagus** [comment]
https://github.com/atom/ci/pull/65 and https://github.com/atom/ci/pull/66 tested from this fixing some annoyances with the AppVeyor builds using the script there. Unfortunately I couldn't find a way to get the NPM output to work properly so we still have to deal with the garbage characters there if we ever need to switch away from the Node.js bundled with APM again.

**Pull request closed without merging**
